"use client";

import { useMemo, useState } from "react";
import { AlertTriangle, BrainCircuit, CheckCircle2, Clock3, Database, GitCompareArrows, LockKeyhole, Play, ShieldCheck, Sparkles } from "lucide-react";
import { Bar, BarChart, CartesianGrid, Line, LineChart, ReferenceLine, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { toast } from "sonner";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import mlPayload from "./data/ml-demo.json";
import statisticalPayload from "./data/forecast-demo.json";

type MLForecast = { series_id:string; label:string; evidence:string; forecast:{period:string;horizon:number;value:number}[] };
type Candidate = { model:string; available:boolean; reason?:string; wape?:number; bias?:number; stability?:number; score?:number };
type Model = Candidate & { version:string; status:string; by_horizon:{horizon:number;observations:number;wape:number;bias:number;stability:number}[] };
type MLPayload = { status:string; cutoff:string; generated_at:string; target:string; dataset:{series:number;observations:number;source:string;excel_required:boolean}; champion:Model; challenger:Model; candidates:Candidate[]; forecast:MLForecast[]; feature_importance:{feature:string;importance:number}[]; drift:{score:number;status:string}; alerts:{type:string;severity:string;message:string}[]; training:{strategy:string;known_features:string[];unknown_features_excluded:string[];duration_seconds:number} };
const ml=mlPayload as MLPayload;
const stat=statisticalPayload as { series:{series_id:string;label:string;target:string;history?:{period:string;actual:number|null}[];forecast?:{period:string;forecast:number|null}[];wape?:number;bias?:number;winner?:string}[] };
const fmt=new Intl.NumberFormat("es-MX",{maximumFractionDigits:0});

function Metric({label,value,detail,tone="blue"}:{label:string;value:string;detail:string;tone?:"blue"|"green"|"amber"|"violet"}) { const colors={blue:"bg-blue-50 text-blue-700",green:"bg-emerald-50 text-emerald-700",amber:"bg-amber-50 text-amber-700",violet:"bg-violet-50 text-violet-700"}; return <Card className="border-slate-200 shadow-sm"><CardContent className="p-5"><div className={`mb-4 grid size-9 place-items-center rounded-xl ${colors[tone]}`}><BrainCircuit className="size-4"/></div><p className="text-sm text-slate-500">{label}</p><p className="mt-1 text-2xl font-semibold tracking-tight">{value}</p><p className="mt-2 text-xs text-slate-500">{detail}</p></CardContent></Card>; }

export default function MLEngineView({supabaseConfigured}:{supabaseConfigured:boolean}) {
  const [target,setTarget]=useState<"Venta"|"Pedido">("Venta");
  const [seriesId,setSeriesId]=useState("total-fendi-bd");
  const selected=ml.forecast.find((row)=>row.series_id===seriesId)??ml.forecast[0];
  const statSeries=stat.series.find((row)=>row.series_id===selected.series_id&&row.target==="Venta")??stat.series.find((row)=>row.series_id==="total-fendi-bd"&&row.target==="Venta");
  const chart=useMemo(()=>{
    const history=(statSeries?.history??[]).slice(-18).map((point)=>({period:point.period,actual:point.actual,statistical:null,ml:null}));
    const futurePeriods=new Set([...(statSeries?.forecast??[]).map((p)=>p.period),...selected.forecast.map((p)=>p.period)]);
    const future=[...futurePeriods].sort().map((period)=>({period,actual:null,statistical:statSeries?.forecast?.find((p)=>p.period===period)?.forecast??null,ml:selected.forecast.find((p)=>p.period===period)?.value??null}));
    return [...history,...future];
  },[selected,statSeries]);
  const divergence=useMemo(()=>{ const stats=statSeries?.forecast??[]; const pairs=selected.forecast.map((p)=>[p.value,stats.find((s)=>s.period===p.period)?.forecast] as const).filter((p):p is readonly[number,number]=>p[1]!=null); return pairs.length?100*pairs.reduce((sum,[m,s])=>sum+Math.abs(m-s)/Math.max(s,1),0)/pairs.length:0; },[selected,statSeries]);

  async function requestTraining(){ if(!supabaseConfigured){toast.warning("Entrenamiento no enviado",{description:"Conecta Supabase para crear una corrida oficial. El Champion visible permanece disponible."});return;} const response=await fetch("/api/ml-runs",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({target})}); if(response.ok)toast.success("Entrenamiento solicitado",{description:"Se creó un Challenger; el Champion no será reemplazado automáticamente."});else toast.error("No fue posible solicitar el entrenamiento"); }

  return <div className="space-y-6">
    <div className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-xs font-bold uppercase tracking-[.16em] text-violet-700">PRD 04 · Modelo global</p><h1 className="mt-2 text-3xl font-semibold tracking-[-.035em]">Motor Machine Learning</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-slate-500">Aprende patrones compartidos entre productos y periodos, con validación temporal y trazabilidad por versión.</p></div><div className="flex flex-wrap gap-2"><Badge variant="outline" className="border-emerald-200 bg-emerald-50 px-3 py-1 text-emerald-700"><LockKeyhole className="mr-1 size-3.5"/> {ml.champion.version}</Badge><Button onClick={requestTraining}><Play/> Solicitar entrenamiento</Button></div></div>
    <div className="rounded-2xl border border-blue-200 bg-blue-50 p-4"><div className="flex gap-3"><ShieldCheck className="mt-0.5 size-5 shrink-0 text-blue-700"/><div><p className="text-sm font-semibold text-blue-950">Champion protegido</p><p className="mt-1 text-sm leading-6 text-blue-800">Un entrenamiento nuevo crea un Challenger. Si falla o no mejora consistentemente, el forecast estadístico y el Champion actual continúan disponibles.</p></div></div></div>
    <Card className="border-slate-200 shadow-sm"><CardContent className="grid gap-4 p-5 md:grid-cols-[220px_1fr_auto]"><label className="space-y-2"><span className="text-xs font-semibold uppercase tracking-wide text-slate-500">Objetivo</span><Select value={target} onValueChange={(value)=>setTarget(value as "Venta"|"Pedido")}><SelectTrigger className="w-full"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="Venta">Venta</SelectItem><SelectItem value="Pedido">Pedido</SelectItem></SelectContent></Select></label><label className="space-y-2"><span className="text-xs font-semibold uppercase tracking-wide text-slate-500">Serie</span><Select value={seriesId} onValueChange={setSeriesId} disabled={target==="Pedido"}><SelectTrigger className="w-full"><SelectValue/></SelectTrigger><SelectContent>{ml.forecast.map((row)=><SelectItem key={row.series_id} value={row.series_id}>{row.label}</SelectItem>)}</SelectContent></Select></label><div className="flex items-end"><div className="rounded-xl bg-slate-50 px-4 py-2.5 text-sm"><span className="text-slate-500">Corte común</span><span className="ml-2 font-semibold">{ml.cutoff}</span></div></div></CardContent></Card>
    {target==="Pedido"?<Card className="border-amber-200"><CardContent className="flex min-h-56 flex-col items-center justify-center p-8 text-center"><AlertTriangle className="size-10 text-amber-500"/><h2 className="mt-4 text-xl font-semibold">Datos insuficientes para Pedido</h2><p className="mt-2 max-w-xl text-sm leading-6 text-slate-500">No hay histórico normalizado de Pedido en el dataset disponible. Venta y Pedido se entrenan por separado; no se creó un objetivo artificial.</p><p className="mt-4 text-xs font-medium text-slate-500">Fallback operativo: Motor Estadístico</p></CardContent></Card>:<>
      <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-5"><Metric label="Champion" value={ml.champion.model.replace(" Global","")} detail={ml.champion.version} tone="violet"/><Metric label="WAPE ML" value={`${ml.champion.wape?.toFixed(1)}%`} detail="Backtesting temporal" tone="amber"/><Metric label="Sesgo ML" value={`${ml.champion.bias!>0?"+":""}${ml.champion.bias?.toFixed(1)}%`} detail={ml.champion.bias!>0?"Subpronóstico":"Sobrepronóstico"} tone="amber"/><Metric label="Estabilidad" value={`${ml.champion.stability?.toFixed(1)}%`} detail="Dispersión del error" tone="blue"/><Metric label="Drift" value={ml.drift.status==="stable"?"Estable":"Atención"} detail={`Score ${ml.drift.score.toFixed(2)}`} tone={ml.drift.status==="stable"?"green":"amber"}/></section>
      <Card className="border-slate-200 shadow-sm"><CardHeader className="flex flex-row items-start justify-between gap-3"><div><CardTitle className="text-base">Real vs. motores</CardTitle><p className="mt-1 text-sm text-slate-500">Mismo corte y periodos para una comparación justa</p></div><Badge variant="outline" className={divergence>20?"border-amber-200 bg-amber-50 text-amber-700":"border-emerald-200 bg-emerald-50 text-emerald-700"}>Divergencia {divergence.toFixed(1)}%</Badge></CardHeader><CardContent><div className="h-[370px]"><ResponsiveContainer width="100%" height="100%" minWidth={0}><LineChart data={chart} margin={{top:8,right:12,left:0,bottom:8}}><CartesianGrid stroke="#e2e8f0" vertical={false}/><XAxis dataKey="period" tick={{fontSize:11,fill:"#64748b"}} minTickGap={24}/><YAxis tickFormatter={(v)=>`${Math.round(Number(v)/1000)}k`} tick={{fontSize:11,fill:"#64748b"}} width={48}/><Tooltip formatter={(value)=>fmt.format(Number(value))}/><ReferenceLine x={ml.cutoff} stroke="#f59e0b" strokeDasharray="4 4" label={{value:"Corte",fontSize:11,fill:"#b45309"}}/><Line type="monotone" dataKey="actual" name="Venta real" stroke="#175cd3" strokeWidth={2.7} dot={false} connectNulls={false}/><Line type="monotone" dataKey="statistical" name="Motor estadístico" stroke="#0f172a" strokeWidth={2.2} strokeDasharray="7 5" dot={false} connectNulls={false}/><Line type="monotone" dataKey="ml" name="Motor ML" stroke="#7c3aed" strokeWidth={2.5} strokeDasharray="2 4" dot={false} connectNulls={false}/></LineChart></ResponsiveContainer></div></CardContent></Card>
      <section className="grid gap-4 xl:grid-cols-[1.15fr_.85fr]"><Card className="border-slate-200 shadow-sm"><CardHeader><CardTitle className="text-base">Modelos candidatos</CardTitle></CardHeader><CardContent className="p-0"><div className="overflow-x-auto"><Table><TableHeader><TableRow className="bg-slate-50"><TableHead>Modelo</TableHead><TableHead>WAPE</TableHead><TableHead>Sesgo</TableHead><TableHead>Estabilidad</TableHead><TableHead>Estado</TableHead></TableRow></TableHeader><TableBody>{ml.candidates.map((row)=><TableRow key={row.model}><TableCell className="font-medium">{row.model}</TableCell><TableCell>{row.available?`${row.wape?.toFixed(1)}%`:"—"}</TableCell><TableCell>{row.available?`${row.bias?.toFixed(1)}%`:"—"}</TableCell><TableCell>{row.available?`${row.stability?.toFixed(1)}%`:"—"}</TableCell><TableCell>{row.model===ml.champion.model?<Badge className="bg-emerald-600">Champion</Badge>:row.model===ml.challenger.model?<Badge variant="outline" className="border-violet-200 bg-violet-50 text-violet-700">Challenger</Badge>:row.available?<span className="text-xs text-slate-500">Evaluado</span>:<span className="text-xs text-slate-400" title={row.reason}>No habilitado</span>}</TableCell></TableRow>)}</TableBody></Table></div></CardContent></Card><Card className="border-slate-200 shadow-sm"><CardHeader><CardTitle className="text-base">WAPE por horizonte</CardTitle></CardHeader><CardContent><div className="h-[310px]"><ResponsiveContainer width="100%" height="100%" minWidth={0}><BarChart data={ml.champion.by_horizon} margin={{top:5,right:8,left:-12,bottom:0}}><CartesianGrid vertical={false} stroke="#e2e8f0"/><XAxis dataKey="horizon" tickFormatter={(v)=>`+${v}`} tick={{fontSize:11,fill:"#64748b"}}/><YAxis unit="%" tick={{fontSize:11,fill:"#64748b"}}/><Tooltip formatter={(value)=>`${value}%`} labelFormatter={(label)=>`Mes +${label}`}/><Bar dataKey="wape" name="WAPE" fill="#7c3aed" radius={[5,5,0,0]}/></BarChart></ResponsiveContainer></div></CardContent></Card></section>
      <section className="grid gap-4 xl:grid-cols-2"><Card className="border-slate-200 shadow-sm"><CardHeader><CardTitle className="text-base">Factores relevantes</CardTitle><p className="text-sm text-slate-500">Estas variables influyeron en la predicción; no implican causalidad.</p></CardHeader><CardContent className="space-y-3">{ml.feature_importance.slice(0,6).map((row)=><div key={row.feature}><div className="mb-1 flex justify-between text-sm"><span className="capitalize text-slate-700">{row.feature}</span><span className="font-semibold">{row.importance.toFixed(1)}%</span></div><div className="h-2 rounded-full bg-slate-100"><div className="h-full rounded-full bg-blue-600" style={{width:`${Math.max(3,row.importance)}%`}}/></div></div>)}</CardContent></Card><Card className="border-slate-200 shadow-sm"><CardHeader><CardTitle className="text-base">Champion vs. Challenger</CardTitle></CardHeader><CardContent className="space-y-4"><ModelRole icon={<CheckCircle2/>} title="Champion publicado" model={ml.champion.model} version={ml.champion.version} wape={ml.champion.wape!} tone="green"/><ModelRole icon={<GitCompareArrows/>} title="Challenger conservado" model={ml.challenger.model} version={ml.challenger.version} wape={ml.challenger.wape!} tone="violet"/><div className="rounded-xl bg-slate-50 p-3 text-xs leading-5 text-slate-600">El Challenger no sustituye al Champion automáticamente. Se conserva para revisión y comparación.</div></CardContent></Card></section>
      <Card className="border-slate-200 shadow-sm"><CardHeader><CardTitle className="text-base">Forecast ML · 12 meses</CardTitle></CardHeader><CardContent className="p-0"><div className="overflow-x-auto"><Table><TableHeader><TableRow className="bg-slate-50">{selected.forecast.map((point)=><TableHead key={point.period} className="min-w-24 text-center">{point.period}</TableHead>)}</TableRow></TableHeader><TableBody><TableRow>{selected.forecast.map((point)=><TableCell key={point.period} className="text-center font-semibold text-violet-700">{fmt.format(point.value)}</TableCell>)}</TableRow></TableBody></Table></div></CardContent></Card>
      <Card className="border-slate-200 shadow-sm"><CardHeader><CardTitle className="text-base">Detalle del modelo</CardTitle></CardHeader><CardContent className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Detail icon={<Database/>} label="Dataset" value={`${ml.dataset.observations} observaciones · ${ml.dataset.series} series`}/><Detail icon={<Clock3/>} label="Entrenamiento" value={`${ml.training.strategy} · ${ml.training.duration_seconds.toFixed(1)} s`}/><Detail icon={<Sparkles/>} label="Variables" value={`${ml.feature_importance.length} principales · esquema completo versionado`}/><Detail icon={<ShieldCheck/>} label="Control" value="Sin fuga · NULL ≠ 0 · outliers conservados"/></CardContent></Card>
    </>}
  </div>;
}

function ModelRole({icon,title,model,version,wape,tone}:{icon:React.ReactNode;title:string;model:string;version:string;wape:number;tone:"green"|"violet"}){return <div className={`rounded-xl border p-4 ${tone==="green"?"border-emerald-200 bg-emerald-50":"border-violet-200 bg-violet-50"}`}><div className="flex gap-3"><div className={`mt-0.5 [&>svg]:size-4 ${tone==="green"?"text-emerald-700":"text-violet-700"}`}>{icon}</div><div><p className="text-sm font-semibold">{title}</p><p className="mt-1 text-sm text-slate-700">{model}</p><p className="mt-1 text-xs text-slate-500">{version} · WAPE {wape.toFixed(1)}%</p></div></div></div>}
function Detail({icon,label,value}:{icon:React.ReactNode;label:string;value:string}){return <div className="flex gap-3 rounded-xl bg-slate-50 p-4"><div className="mt-0.5 text-blue-700 [&>svg]:size-4">{icon}</div><div><p className="text-xs font-bold uppercase tracking-wide text-slate-500">{label}</p><p className="mt-1 text-sm leading-5 text-slate-700">{value}</p></div></div>}
